DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Relationship CASCADE;
DROP TABLE IF EXISTS LookingFor CASCADE;
DROP TABLE IF EXISTS Message CASCADE;
DROP TABLE IF EXISTS Page CASCADE;
DROP TABLE IF EXISTS Invoice CASCADE;
DROP TABLE IF EXISTS Access CASCADE;

